
require:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec

AllCops:
  Exclude:
    - "vendor/**/*"
    - "db/**/*"
    - "config/**/*"
    - "bin/*"
    - "node_modules/**/*"

Layout/LineLength:
  Enabled: false
  AllowedPatterns:
    - "Rakefile"
    - "spec/rails_helper.rb"
    - "spec/spec_helper.rb"
    


Metrics/AbcSize:
  Max: 50

Metrics/PerceivedComplexity:
  Max: 8

Metrics/MethodLength:
  Max: 30

Metrics/ClassLength:
  Max: 100  # 適切な値に設定してください


Style/EmptyMethod:
  EnforcedStyle: expanded

Style/ClassAndModuleChildren:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false